### PR TITLE
Add basic QR scan functionality

### PR DESCRIPTION
**Pull request by devbridie**
- Adds button in main activity.
- Adds QR code library (`me.dm7.barcodescanner:zxing:1.9.8`)
- Adds `ScanQRActivity` which requests Camera permissions and shows the camera preview.
- When a QR code is scanned, the information is displayed in an AlertDialog.

### CODE REVIEW

**Comment by synctext** [comment]
upstream app changed a lot, big overlay PR got merged. Rebase...

**Comment by devbridie** [comment]
I have rebased our changes on top of the upstream app.

I have also attached an image of a QR exported our version of tribler that can export keys. QR

**Comment by wkmeijer** [comment]
@devbridie and others, any update on my question above about the validation error? Do you have the same issues or is it something that went wrong on my end?

**Comment by PauluzzNL** [comment]
To test the latest code, there is a screenshot of a QR code on the issue https://github.com/Tribler/tribler/issues/3239#issuecomment-357920863

**Comment by devbridie** [comment]
The import QR code functionality has since been revised such that no keys are replaced anymore. Therefore, any functionality regarding keys should work as normal. However, on my phone, I am not able to connect to a peer even with your current master, so I cannot verify if our PR will break functionality.

**Comment by synctext** [comment]
please retry @devbridie 
Booststrap phone just re-started.
Updated the app on bootstrap phone at 12:30-ish today. Now seems slightly more stable.

**Comment by synctext** [comment]
never, mind, just checked, bootstrap phone crashed again in a few minutes :-(

**Comment by PauluzzNL** [comment]
@synctext Do you have more information on the crash? At what point did it crash? During startup, during QR scanning? We tested this code on 3 different android phones and we had no issues whatsoever.

**Comment by PauluzzNL** [comment]
We just tested the latest version (this PR request's code) and it starts fine. Is there anything blocking this PR from merging? Could we otherwise get more information on the crash, as this might be related to already existing (overlay) code, instead of the added QR import code?

Below is a screenshot which I see if I start the app now, it seems to connect to other peers.

photo_2018-01-16_17-09-33

**Comment by PauluzzNL** [comment]
For testing purposes here are four scannable QR codes:
qr1
qr2
qr3
qr4

**Comment by wkmeijer** [comment]
@PauluzzNL 

From a clean install, as soon as I try to connect to someone I get:

```
I/nl.tudelft.cs4160.trustchain_android.connection.network.ClientTask: Sent crawl request to peer with ip 192.168.43.184:1873
I/nl.tudelft.cs4160.trustchain_android.connection.Communication: Received half block from peer with IP: 192.168.43.184:8080 and public key: 120D67F4B6710E897DB4810BA937D0E2FC15065FCDE1A384FF57DEA44104C77C
I/nl.tudelft.cs4160.trustchain_android.connection.Communication: Received block validation result <ValidationResult: INVALID>(Trustchainblock: {
    Public key: 120D67F4B6710E897DB4810BA937D0E2FC15065FCDE1A384FF57DEA44104C77C
    Sequence Number: 1
    Link Public Key: 00
    Link Sequence Number: 0
    Previous Hash: 00
    Signature: 220FCF4095E32C360210C41C46660985594BCF0DDC154BEF75A837746462A38C711C26CA586FC3C7E50EBDCD6988A552F5B9014655093116FF019E3BFAB9240D
    Transaction:
})
E/nl.tudelft.cs4160.trustchain_android.connection.Communication: Validation error: Invalid signature.
```

This is because the signing and verifying does not work properly since you've started to use libsodium. Something simple as:

``
KeyPair pair = Key.createNewKeyPair();
byte[] message = {(byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00};
byte[] signature = Key.sign(pair.getPrivateKey(), message);
Key.verify(pair.getPublicKey(), message, signature)
``

Will yield false for the verify. Please try to fix this and verify that it is fixed by writing some tests.

Furthermore the qr scan button in TrustChainActivity seems to be redundant. And should the funds activity show something new after importing a new wallet? Because it doesn't for me.

**Comment by PauluzzNL** [comment]
@wkmeijer We're working on it now, will have a status update this afternoon. Are you available this afternoon so we can go through it without going back and forth on a ticket?

**Comment by wkmeijer** [comment]
@PauluzzNL 
I'm available from 14.30-17.30, where do you want to meet?

**Comment by PauluzzNL** [comment]
@wkmeijer Is 16.00 okay? In that case let's meet up at the 3rd floor in the new building and we can find a place there.

**Comment by wkmeijer** [comment]
@PauluzzNL sure

**Pull request merged**
