### PR TITLE
Merge overlay and wallet

### PR DESCRIPTION
**Pull request by klikooo**

### CODE REVIEW

**Comment by PauluzzNL** [comment]
@klikooo if you have questions regarding our code with merging please drop a note. A lot of things have changed, especially since the complete crypto library was replaced.

**Comment by klikooo** [comment]
@PauluzzNL I have merged the two branches in this branch https://github.com/wkmeijer/CS4160-trustchain-android/tree/merge-wallet-overlay. I don't know if i have removed some functionality of your pr, so is possible you can check if i did not miss a thing.

Next to this, the export activity crashes when I try to open it, resulting in the following error
```
java.lang.ExceptionInInitializerError: 
  at nl.tudelft.cs4160.trustchain_android.message.MessageProto$TrustChainBlock.getDescriptor (MessageProto.java:928)
  at nl.tudelft.cs4160.trustchain_android.message.MessageProto$TrustChainBlock.hashCode (MessageProto.java:1110)
  at nl.tudelft.cs4160.trustchain_android.qr.ExportWalletQRActivity.exportQRCode (ExportWalletQRActivity.java:126)
  at nl.tudelft.cs4160.trustchain_android.qr.ExportWalletQRActivity.access$000 (ExportWalletQRActivity.java:39)
  at nl.tudelft.cs4160.trustchain_android.qr.ExportWalletQRActivity$1.run (ExportWalletQRActivity.java:54)
  at java.lang.Thread.run (Thread.java:833)
Caused by: java.lang.IllegalArgumentException: 
  at com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom (Descriptors.java:341)
  at nl.tudelft.cs4160.trustchain_android.message.MessageProto.<clinit> (MessageProto.java:2255)
Caused by: com.google.protobuf.InvalidProtocolBufferException: 
  at com.google.protobuf.CodedInputStream$ArrayDecoder.checkLastTagWas (CodedInputStream.java:617)
  at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage (CodedInputStream.java:875)
  at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init> (DescriptorProtos.java:1212)
  at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init> (DescriptorProtos.java:1135)
  at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom (DescriptorProtos.java:4655)
  at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom (DescriptorProtos.java:4650)
  at com.google.protobuf.AbstractParser.parsePartialFrom (AbstractParser.java:163)
  at com.google.protobuf.AbstractParser.parseFrom (AbstractParser.java:196)
  at com.google.protobuf.AbstractParser.parseFrom (AbstractParser.java:209)
  at com.google.protobuf.AbstractParser.parseFrom (AbstractParser.java:214)
  at com.google.protobuf.AbstractParser.parseFrom (AbstractParser.java:49)
  at com.google.protobuf.DescriptorProtos$FileDescriptorProto.parseFrom (DescriptorProtos.java:2154)
  at com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom (Descriptors.java:339)
```

I haven't had much time to look at it, so it might be something trivial

**Comment by wkmeijer** [comment]
@klikooo The crash on Export Tokens must have something to do with the merging, because it was working before. So that's the functionality you have removed. :smile:

**Comment by wkmeijer** [comment]
@klikooo I think this is a bug they showed me earlier, it is caused by unexpected blocks. The export funds functionality expects a certain pattern for a block (namely the tribler pattern) and doesn't account for other blocks to be present in the chain. So it crashes when it encounters a block without a specific json formatted transaction.

**Comment by klikooo** [comment]
See #77

**Pull request closed without merging**
